# config.make generated by configure script
POCO_CONFIG=Linux-clang
POCO_BASE=/Users/alex/ci/docker
POCO_BUILD=/Users/alex/ci/docker
POCO_FLAGS=
POCO_GIT_BRANCH=develop
POCO_CC_COMPILER=clang
POCO_CXX_COMPILER=clang++
POCO_COMPILER_VERSION=4.0
POCO_BITS=64
POCO_PREFIX=/usr/local
OMIT='Crypto NetSSL_OpenSSL Zip Data Data/SQLite Data/ODBC Data/MySQL Data/PostgreSQL MongoDB Redis PDF CppParser PageCompiler'
POCO_OMIT=Crypto,NetSSL_OpenSSL,Zip,Data,Data/SQLite,Data/ODBC,Data/MySQL,Data/PostgreSQL,MongoDB,Redis,PDF,CppParser,PageCompiler
POCO_CI_CONTAINER_NAME=poco-develop-clang-4.0-Linux-clang
export POCO_CONFIG
export POCO_FLAGS
export POCO_GIT_BRANCH
export POCO_CC_COMPILER
export POCO_CXX_COMPILER
export POCO_COMPILER_VERSION
export POCO_BITS
export POCO_OMIT
export POCO_CI_CONTAINER_NAME
export POCO_PREFIX
