#!/bin/bash
#
# usage:
#
# run-ci.sh [action [-d]]
#

arg1=$1
arg2=$2
if [ "$arg1" == "" ] ; then
	arg1="up"
	arg2="-d"
fi

source config.build
source config.make

if [ "$(docker ps -a | grep $POCO_CI_CONTAINER_NAME)" ]; then
	docker rm -f $POCO_CI_CONTAINER_NAME
fi

if [ "$COMPOSE_PROJECT_NAME" == "" ]; then
	export COMPOSE_PROJECT_NAME=`pwd`
fi

COMPOSE_FILE="$COMPOSE_PROJECT_NAME/docker-compose.yml"
echo "docker-compose -f $COMPOSE_FILE $arg1 $arg2"
docker-compose -f $COMPOSE_FILE $arg1 $arg2
